### PR TITLE
Serg

### PR DESCRIPTION
**Pull request by Serg-Bartosh**

### CODE REVIEW

**Comment by Serg-Bartosh** [comment]
@s373r . plz check new changes аnd add @Alena-bartosh

**Comment by alena-bartosh** [comment]
Hello. I was added again :)

Have a few questions and small tips:

1. Why do you remove all files?
2. What is `problem_solving`? Please notice that all files should be with some extensions (f.g. `.py` or `.txt` etc.)
3. Name of each PR is very important, because on real job people will take it into account before open. So you should change it to more informative. Like "Remove all files from project and add problem_solving" (but read 1, 2 please)
4. Each Pull Request has a description. If your changes are very little, then it can stay empty, but in another case you should write shortly WHAT (point 2 from my list) you do and WHY (point 1) you do it.

😉

**Comment by alena-bartosh** [comment]
Also each PR has `Reviewers` and `Assignees` (right panel). Please fill out `Reviewers` when you want to get code review, and `Assignees` is always you (in our case).

**Comment by Serg-Bartosh** [comment]
@alena-bartosh , I suggest deleting **all files**, as they are **unnecessary**. I created a "`problem_solving`" file. There I think to place my tasks from courses, etc.

**Comment by Serg-Bartosh** [comment]
> Also each PR has `Reviewers` and `Assignees` (right panel). Please fill out `Reviewers` when you want to get code review, and `Assignees` is always you (in our case).

```
word = ['г','е','н','и','й']

for i in range(len(word)):
    print(word[i])
```

**Comment by Serg-Bartosh** [comment]
Hello everyone, I have a question, can I transfer my commits to a profile?
@alena-bartosh 
@s373r

**Comment by alena-bartosh** [comment]
> can I transfer my commits to a profile?

It is a good question @Serg-Bartosh . Let's close this PR and be clear about some things.

1. This project is **only** for you **git** studies. For cources please create new project on your profile (I see [you already did it](https://github.com/Serg-Bartosh?tab=repositories)).
2. You want to save **all** tasks, so please do not remove code like [here](https://github.com/Serg-Bartosh/My_road/commit/7da7af3caee17400ba5c3dd01ce978bb7d5818cf). If you remove something, it does not make sense because commits history is not important. In the results, we should have **different files for different tasks**.

For example, my repository: https://github.com/alena-bartosh/stepic-courses/tree/main/data_structures/week_1

❗❗❗
```
One file = one commit 
One task = one file
```
In your case, you save only latest task.

**Pull request closed without merging**
